# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - follow_joint_trajectory
    - gripper_command

  follow_joint_trajectory:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    action_ns: follow_joint_trajectory
    default: true
  gripper_command:
    type: GripperCommand
    joints:
      - joint_5
      - joint_6
      - joint_7
    action_ns: gripper_cmd
    default: true