controller_manager:
  ros__paramters:
    update_rate: 100 # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      joint_1: { trajectory: 0.2, goal: 0.1 }
      joint_2: { trajectory: 0.2, goal: 0.1 }
      joint_3: { trajectory: 0.2, goal: 0.1 }
      joint_4: { trajectory: 0.2, goal: 0.1 }
      joint_5: { trajectory: 0.2, goal: 0.1 }
      joint_6: { trajectory: 0.2, goal: 0.1 }
      joint_7: { trajectory: 0.2, goal: 0.1 }